### ISSUE TITLE
Output of rule splign - where is it used?

### ISSUE THREAD

**Issue by nickloman** [WatsonLab/sm_assemblies#1]
Hi Mick

I've tried to run this pipeline and am able to get to the splign step which produces directories entitled <genome>splign/CDS with a subdir for each transcript. However I cannot see where these directories are used to produce the final output, e.g. broken gene statistics for the pipeline. Can you clarify what needs to happen after run_splign.pl step?

Best
Nick

**Comment by mw55309** [comment]
Hi Nick

Two things on this:

1). I uploaded a new version of the run_splign.pl script that now aligns the top two hits for each CDS, rather than the top 1.  The reason for this is that we discovered that the pipeline was picking up un-spliced pseudogenes as the top hit, and the "real" spliced gene as a second hit.  Therefore run_splign.pl now considers the two top hits.  This change improved stats for all assemblies, therefore I recommend you re-run splign.

2). The perl script in scripts/alnparse.pl should summarise the splign outputs into a use-able format for reporting.  The README gives brief documentation.

HTH

Cheers
Mick
